minipo_homepage:
    path:     /
    defaults: { _controller: minipoBundle:Default:indexclientexterne }
minipo_client:
    path:     /client/
    defaults: { _controller: minipoBundle:Default:client }
minipo_employe:
    path:     /employe/
    defaults: { _controller: minipoBundle:Default:employe }
minipo_admin:
    path:     /admin/
    defaults: { _controller: minipoBundle:Default:admin }
minipo_Afficher:
    path:     /adminRH/AfficherEmploye
    defaults: { _controller: minipoBundle:Employe:trouverEmploye }
minipo_editEmploye:
    path:     /adminRH/edit/{id}
    defaults: { _controller: minipoBundle:Employe:edit }
minipo_updateEmploye:
    path:     /adminRH/update/{id}
    defaults: { _controller: minipoBundle:Employe:update }
minipo_delete:
    path:     /adminRH/delete/{id}
    defaults: { _controller: minipoBundle:Employe:delete }
minipo_Ajouter:
    path:     /adminRH/AjouterEmploye
    defaults: { _controller: minipoBundle:Employe:Ajouter }
minipo_Affecter:
    path:     /adminRH/AffecterEquipe
    defaults: { _controller: minipoBundle:Equipe:Affecter }
minipo_Equipe:
    path:     /adminRH/GererEquipe
    defaults: { _controller: minipoBundle:Equipe:Equipe }
minipo_deleteEquipe:
    path:     /adminRH/deleteEquipe/{id}
    defaults: { _controller: minipoBundle:Equipe:delete }
minipo_updateEquipe:
    path:     /adminRH/updateEquipe/{id}
    defaults: { _controller: minipoBundle:Equipe:update }
minipo_AfficherToutesReclamation:
    path:   /admin/afficher
    defaults: { _controller: minipoBundle:ServiceReclamationClient:AfficherToutesReclamation}
minipo_AjouterReclamation:
    path:   /client/ajouter
    defaults: { _controller: minipoBundle:ServiceReclamationClient:AjouterReclamation}
minipo_AfficherMesReclamation:
    path:   /client/afficherMesReclamation
    defaults: { _controller: minipoBundle:ServiceReclamationClient:AfficherMesReclamation}
minipo_showdetailed:
    path:   /client/showdetailed/{id}
    defaults: { _controller: minipoBundle:ServiceReclamationClient:showdetailedClient}

minipo_ModifierEtatReclamation:
    path:   /admin/modifieretat/{id}
    defaults: { _controller: minipoBundle:ServiceReclamationClient:ModifierEtatReclamation}
minipo_SupprimerReclamation:
    path:   /admin/afficher/supprimer/{etatr}
    defaults: { _controller: minipoBundle:ServiceReclamationClient:SupprimerReclamation}
minipo_searchClub:
    path:   /admin/RechercheReclamation
    defaults: { _controller: minipoBundle:ServiceReclamationClient:searchClub}
minipo_showdetailedEmploye:
    path:   /employe/showdetailed/{id}
    defaults: { _controller: minipoBundle:ServiceReclamationEmploye:showdetailedEmploye}
minipo_AfficherToutesReclamationEmploye:
    path:   /admin/afficheremployer/
    defaults: { _controller: minipoBundle:ServiceReclamationEmploye:AfficherToutesReclamationEmploye}

minipo_ModifierEtatReclamationEmploye:
    path:   /modifieretatemploye/{id}
    defaults: { _controller: minipoBundle:ServiceReclamationEmploye:ModifierEtatReclamationEmploye}
minipo_SupprimerReclamationEmploye:
    path:   /afficher/supprimerEmploye/{etatr}
    defaults: { _controller: minipoBundle:ServiceReclamationEmploye:SupprimerReclamationEmploye}
minipo_AjouterReclamationEmploye:
    path:   /employe/ajouterEmploye
    defaults: { _controller: minipoBundle:ServiceReclamationEmploye:AjouterReclamationEmploye}

minipo_Search:
    path:   /employe/SearchEmploye
    defaults: { _controller: minipoBundle:ServiceReclamationEmploye:ajaxList}


minipo_AfficherMesReclamationEmployes:
    path:   /employe/AfficherMesReclamationEmployes
    defaults: { _controller: minipoBundle:ServiceReclamationEmploye:AfficherMesReclamationEmploye}
minipo_commandesClt:
    path:     /client/MesCmd
    defaults: { _controller: minipoBundle:Commande:commandesClt }
minipo_reclamationcommande:
    path:     /client/reccmd/{idcmd}
    defaults: { _controller: minipoBundle:ServiceReclamationClient:AjouterReclamationCommande }
minipo_Stat:
    path:     /admin/stat
    defaults: { _controller: minipoBundle:Stat:StatRecClt }
