minipo_homepage:
    path:     /
    defaults: { _controller: minipoBundle:Default:indexclientexterne }
minipo_client:
    path:     /client/
    defaults: { _controller: minipoBundle:Default:client }
minipo_employe:
    path:     /employe/
    defaults: { _controller: minipoBundle:Default:employe }
minipo_admin:
    path:     /admin/
    defaults: { _controller: minipoBundle:Default:admin }
minipo_afficheLiv:
    path:     /admin/affiche
    defaults: { _controller: minipoBundle:LivraisonBack:afficheLiv }
minipo_ajoutliv:
    path:     /admin/ajout
    defaults: { _controller: minipoBundle:LivraisonBack:ajoutliv }
minipo_update:
    path:     /admin/update/{id}
    defaults: { _controller: minipoBundle:LivraisonBack:updateLiv }
minipo_delete:
    path:     /admin/delete/{id}
    defaults: { _controller: minipoBundle:LivraisonBack:Delete }
minipo_afficheLivreur:
    path:     /livreur/afficheLivreur
    defaults: { _controller: minipoBundle:LivraisonFront:afficheLivreur }
minipo_updateEtat:
    path:     /livreur/updateEtat/{id}
    defaults: { _controller: minipoBundle:LivraisonFront:updateEtat }
minipo_searchByEtat:
    path:     /livreur/searchByEtat
    defaults: { _controller: minipoBundle:LivraisonFront:searchByEtat }
minipo_searchByDest:
    path:     /livreur/searchByDest
    defaults: { _controller: minipoBundle:LivraisonFront:searchByDest }
minipo_search:
    path:     /livreur/search
    defaults: { _controller: minipoBundle:LivraisonFront:search }
minipo_mail:
    path:     /admin/mail/{name}
    defaults: { _controller: minipoBundle:LivraisonBack:mail }
minipo_details:
    path:     /admin/details/{id}
    defaults: { _controller: minipoBundle:LivraisonBack:details }