minipo_homepage:
    path:     /
    defaults: { _controller: minipoBundle:Default:indexclientexterne }
minipo_client:
    path:     /client/
    defaults: { _controller: minipoBundle:Default:client }
minipo_employe:
    path:     /employe/
    defaults: { _controller: minipoBundle:Default:employe }
minipo_admin:
    path:     /admin/
    defaults: { _controller: minipoBundle:Default:admin }
minipo_Afficher:
    path:     /adminRH/AfficherEmploye
    defaults: { _controller: minipoBundle:Employe:trouverEmploye }
minipo_editEmploye:
    path:     /adminRH/edit/{id}
    defaults: { _controller: minipoBundle:Employe:edit }
minipo_updateEmploye:
    path:     /adminRH/update/{id}
    defaults: { _controller: minipoBundle:Employe:update }
minipo_delete:
    path:     /adminRH/delete/{id}
    defaults: { _controller: minipoBundle:Employe:delete }
minipo_Ajouter:
    path:     /adminRH/AjouterEmploye
    defaults: { _controller: minipoBundle:Employe:Ajouter }
minipo_AjouterEmp:
    path:     /adminRH/AjouterEmploye1
    defaults: { _controller: minipoBundle:Employe:Ajouter2 }
minipo_Affecter:
    path:     /adminRH/AffecterEquipe
    defaults: { _controller: minipoBundle:Equipe:Affecter }
minipo_Equipe:
    path:     /adminRH/GererEquipe
    defaults: { _controller: minipoBundle:Equipe:Equipe }
minipo_deleteEquipe:
    path:     /adminRH/deleteEquipe/{id}
    defaults: { _controller: minipoBundle:Equipe:delete }
minipo_updateEquipe:
    path:     /adminRH/updateEquipe/{id}
    defaults: { _controller: minipoBundle:Equipe:update }
minipo_BilanRH:
    path:     /adminRH/Bilan
    defaults: { _controller: minipoBundle:Bilan:index}
minipo_AjouterConge:
    path:     /employe/AjouterConge
    defaults: { _controller: minipoBundle:Employe:AjouterConge}
minipo_AfficherConge:
    path:     /employe/AfficherConge
    defaults: { _controller: minipoBundle:Employe:AfficherConge}
minipo_AfficherEmployeConge:
    path:     /adminRH/AfficherEmployeConge
    defaults: { _controller: minipoBundle:Employe:AfficherEmployeEnConge}
minipo_DemandeConge:
    path:     /adminRH/DemandeConge
    defaults: { _controller: minipoBundle:Employe:DemandeConge}
minipo_AccepterConge:
    path:     /adminRH/AccepterConge/{id}
    defaults: { _controller: minipoBundle:Employe:AccepterConge}